---
kind: Service
apiVersion: v1
metadata:
  name: proxy-service
  namespace: {{NAMESPACE}}
  labels:
    dns: route53
  annotations:
    domainName: "{{DOMAIN}}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: |-
      {{SSL_CERT}}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer
  selector:
    app: proxy-container
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-container
  template:
    metadata:
      labels:
        app: proxy-container
    spec:
      containers:
        - name: proxy
          image: unicef/etools-prp-nginx-proxy:{{CF_SHORT_REVISION}}
          volumeMounts:
            - name: static-volume-{{NAMESPACE}}
              mountPath: /data
          ports:
            - containerPort: 80
              hostPort: 30080
          env:
            - name: DJANGO_APPLICATION_SERVICE_HOST
              value: backend
            - name: DJANGO_NGINX_SERVER_NAME
              value: prp.tivixlabs.com
            - name: HTTPS_REDIRECT
              value: "1"
      volumes:
      - name: static-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: data-volume-claim-{{NAMESPACE}}